const skills = {
	"ALGEBRA/ACT": ["ABDELALI", "ABIRAMI", "ANGELA", "ANTHONY", "ANTONIO", "ARTA", "ARTJOLA", "CHANICE", "DAHIANA", "GEORGE", "JOSEMARY", "COLLADO", "JULINDA", "LEYLA", "MBAYE", "MOBASSARA", "NASLEY", "RENE", "RICK", "THYRA", "VILMANIA", "YANILDA", "YULUISKA"],
	"CALCULUS": ["ABDELALI", "ABIRAMI", "ARTJOLA", "DAHIANA", "GEORGE", "JULINDA", "MBAYE", "MOBASSARA", "NASLEY", "RICK", "VILMANIA", "YULUISKA"], 
	"STATISTICS": ["ANTHONY", "ANTONIO", "ARTA", "GEORGE", "JOSEMARY", "JULINDA", "LEYLA", "MBAYE", "MOBASSARA", "RICK", "THYRA"],
	"PRE-CALCULUS": ["ABDELALI", "ABIRAMI", "ANGELA", "ANTHONY", "ANTONIO", "DAHIANA", "GEORGE", "JULINDA", "LEYLA", "MBAYE", "MOBASSARA", "NASLEY", "RICK", "THYRA", "VILMANIA", "YULUISKA"],
	"MAPLE": ["ABIRAMI","ARTJOLA", "COLLADO", "MBAYE", "MOBASSARA"],
	"PYTHON": ["ABIRAMI", "ARTJOLA", "CHANICE", "COLLADO", "ORELLANA", "YANILDA"], 
	"JAVA": ["CHANICE", "COLLADO", "ORELLANA", "YANILDA"], 
	"ALL COURSES": ["ABDELALI", "ABIRAMI", "ANGELA", "ANTHONY", "ANTONIO", "ARTA", "ARTJOLA", "CHANICE", "DAHIANA", "GEORGE", "JOSEMARY", "COLLADO", "JULINDA", "LEYLA", "MBAYE", "MOBASSARA", "NASLEY", "RENE", "RICK", "THYRA", "VILMANIA", "YANILDA", "YULUISKA","ORELLANA"]
}
export default skills;