const tutors = {
"ABDELALI": {"photo": "images/person-placeholder.jpg"},
"ABIRAMI": {"photo": "images/person-placeholder.jpg"},
"ANGELA": {"photo": "images/person-placeholder.jpg"},
"ANTHONY": {"photo": "images/person-placeholder.jpg"},
"ANTONIO": {"photo": "images/person-placeholder.jpg"},
"ARTA": {"photo": "images/person-placeholder.jpg"},
"ARTJOLA": {"photo": "images/person-placeholder.jpg"},
"CHANICE": {"photo": "images/person-placeholder.jpg"}, 
"COLLADO": {"photo": "images/person-placeholder.jpg"},
"DAHIANA": {"photo": "images/person-placeholder.jpg"},
"GEORGE": {"photo": "images/person-placeholder.jpg"},
"HASAN": {"photo": "images/person-placeholder.jpg"}, 
"JOSEMARY": {"photo": "images/person-placeholder.jpg"},
"JULINDA": {"photo": "images/person-placeholder.jpg"},
"LEYLA": {"photo": "images/person-placeholder.jpg"},
"MBAYE": {"photo": "images/person-placeholder.jpg"},
"MOBASSARA": {"photo": "images/person-placeholder.jpg"},
"NASLEY": {"photo": "images/person-placeholder.jpg"},
"ORELLANA": {"photo": "images/person-placeholder.jpg"}, 
"RENE": {"photo": "images/person-placeholder.jpg"},
"RICK": {"photo": "images/person-placeholder.jpg"},
"THYRA": {"photo": "images/person-placeholder.jpg"},
"VILMANIA": {"photo": "images/person-placeholder.jpg"},
"YANILDA": {"photo": "images/person-placeholder.jpg"},
"YULUISKA": {"photo": "images/person-placeholder.jpg"}
}
export default tutors;